[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="sec" type="cr.onion.web.variable.SecurityVariable" --]
[#-- @ftlvariable name="user" type="cr.onion.web.variable.UserVariable" --]
[#-- @ftlvariable name="topicCategory" type="cr.onion.entity.TopicCategory" --]
[#macro topic_category id][/#macro]
