[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="sec" type="cr.onion.web.variable.SecurityVariable" --]
[#-- @ftlvariable name="onion" type="cr.onion.web.variable.OnionVariable" --]
[#-- @ftlvariable name="topicCategory" type="cr.onion.entity.TopicCategory" --]
[#macro topic_category id=""][/#macro]
